CREATE TABLE ShaniceShoes (id INTEGER PRIMARY KEY, brandname TEXT, quantity INTEGER, color TEXT, price INTEGER);
INSERT INTO ShaniceShoes VALUES (1, "Yeezy Seven Hundred", 5, "BLUSH", 350);
INSERT INTO ShaniceShoes VALUES (2, "Jordan One", 3, "MOCHA", 300);
INSERT INTO ShaniceShoes VALUES (3, "Jordan Three", 7, "CEMENTS", 275);
INSERT INTO ShaniceShoes VALUES (4, "Yeezy Three Fifty", 1, "YEEZREAL", 300);
INSERT INTO ShaniceShoes VALUES (5, "Yeezy Seven Fifty", 5, "YEEZREAL", 325);
INSERT INTO ShaniceShoes VALUES (6, "Converse",12, "BLACK",125);
INSERT INTO ShaniceShoes VALUES (7, "Yeezy Seven Hundred", 5, "YEEZREAL",315);
INSERT INTO ShaniceShoes VALUES (8, "Jordan One", 8, "BRED",400);
INSERT INTO ShaniceShoes VALUES (9, "Jordan Three", 5, "ANIMALISTIC",275);
INSERT INTO ShaniceShoes VALUES (10, "Jordan One", 3, "GATORADE YELLOW",275);
INSERT INTO ShaniceShoes VALUES (11, "Yeezy", 5, "MOACHA",425);
INSERT INTO ShaniceShoes VALUES (12, "Yeezy Three Fifty", 2, "YEEZREAL",335);
INSERT INTO ShaniceShoes VALUES (13, "Nike Dunks", 9, "PANDA",345);
INSERT INTO ShaniceShoes VALUES (14, "Jordan Eleven", 8, "COOL GREY",415);
INSERT INTO ShaniceShoes VALUES (15, "Jordan One", 15, "OREO",210);
SELECT brandname FROM ShaniceShoes ORDER BY id; 
SELECT price, brandname, color FROM ShaniceShoes;
SELECT MAX(price) FROM ShaniceShoes;
SELECT MIN(price) FROM ShaniceShoes;
SELECT SUM(price) FROM ShaniceShoes;
SELECT count(quantity) FROM ShaniceShoes;
